### ISSUE TITLE
Trial expired notification popup appears after freezing trial in a few days

### ISSUE THREAD

**Issue by Nvdtn19** [WindowsAddict/IDM-Activation-Script#31] opened 2024-04-02 13:25 UTC
Hi, after a few days freezing the trial time, IDM is working properly and there's no annoying popups I see. But now, this popup suddenly appears in my computer today. It says trial is expired and i need to register. It started to show again after i close it for a certain of time, but I don't know whether after how many minutes the popup would showing back. However, it does not affect the usage of IDM and still let me download things. Therefore I redownloaded the tool and refreeze the trial again to follow if that popup still appears or not. So, I want to know is there's any chance that you could find ways to block this popup as well? 
![Screenshot (10)](https://github.com/WindowsAddict/IDM-Activation-Script/assets/115412489/45976f9d-b1ff-4e1e-b457-c5f13c441100)

**Comment by WindowsAddict** [comment] 2024-04-02 13:41
@Nvdtn19 
Use reset option in IAS script and then use freeze trial option.
Share screenshot if that popup appears again.

**Comment by raycao-git** [comment] 2024-04-02 13:49
Me too.
Used reset option in IAS script and then use freeze trial option.
It will pop up again after downloaded a file.

**Comment by hhoneeyy** [comment] 2024-04-02 16:44
try uninstalling idm and then using the freeze trial option again

**Comment by WindowsAddict** [comment] 2024-04-02 19:24
@Nvdtn19 @raycao-git 
Did you ensure that no other crack is applied and IDM was installed using original installer and then freeze trial option was applied?

**Comment by 4evermaat** [comment] 2024-04-03 01:45
I see on 2 different computers that are using IDM that the OP's issue is happening.   (getting prompted that the trial has ended. and prompts for payment.

But it seems the program still works though (for now).

I thought the trial reset would be perpetual.   But you are saying that it must be re-run every so often?

**Comment by lunarwolfspirit** [comment] 2024-04-03 03:14
I too had the same pop-up today, but I'm not sure if its pure coincidence cause I made some changes. 

I had just disabled Chrome integration previously but happened to re-enable it today, while also re-installing the extension directly from their website. Got a pop-up pretty soon afterwards.

I didn't uninstall but tried to reset the trial and reactivate but still got a pop-up shortly after.

Will try and re-install later today and let you know how that goes...

**Comment by beifangpoi** [comment] 2024-04-03 03:18
I have the same question.This issue occurred after updating version Version 6.42 Build 7  (Mar/25/2024)

**Comment by WindowsAddict** [comment] 2024-04-03 04:19
@4evermaat @lunarwolfspirit @beifangpoi 
Did you guys use any other crack to activate IDM?
Did you ensure that IDM was installed using original installer and then freeze trial option was applied?

**Comment by lunarwolfspirit** [comment] 2024-04-03 05:46
> @4evermaat @lunarwolfspirit @beifangpoi Did you guys use any other crack to activate IDM? Did you ensure that IDM was installed using original installer and then freeze trial option was applied?

Never used any other method of activation. 

However, I just uninstalled, restarted, re-downloaded, re-installed, reset and re-armed. No popups so far any more.

**Comment by WindowsAddict** [comment] 2024-04-03 05:50
@lunarwolfspirit Let me know if you get the popup again.

**Comment by DeepM9700** [comment] 2024-04-03 08:22
> @lunarwolfspirit Let me know if you get the popup again.

It's been happening for 1 week now, however, I have noticed 1 thing, with the activation option of your tool it says the IDM trial will expire in N days and with the freeze trial it says the free trial is over. Either way, it does not stay activated

**Comment by beifangpoi** [comment] 2024-04-03 08:35
> 你们有没有使用任何其他破解来激活 IDM？您是否确保使用原始安装程序安装了 IDM，然后应用了冻结试用选项？

I have returned version 6.42 Build 3 and after re freezing, everything is currently normal without cleaning up the data

**Comment by raycao-git** [comment] 2024-04-03 08:45
> > 你们有没有使用任何其他破解来激活 IDM？您是否确保使用原始安装程序安装了 IDM，然后应用了冻结试用选项？
> 
> I have returned version 6.42 Build 3 and after re freezing, everything is currently normal without cleaning up the data

yes,me too,but need reboot

**Comment by YuriKharkov** [comment] 2024-04-03 09:33
I can confirms its happening again, I have no crack installed. Even fully uninstalled IDM, downloaded the latest original version and ran the script afresh, still payment is popping up. They have wised up.

**Comment by raycao-git** [comment] 2024-04-03 10:25
> > > 你们有没有使用任何其他破解来激活 IDM？您是否确保使用原始安装程序安装了 IDM，然后应用了冻结试用选项？
> > 
> > 
> > I have returned version 6.42 Build 3 and after re freezing, everything is currently normal without cleaning up the data
> 
> yes,me too,but need reboot

The pop-up started again

**Comment by emikoyamasaki** [comment] 2024-04-03 11:08
Same issue. I uninstalled and reinstalled using the default method so as to preserve my download list.

**Comment by 4evermaat** [comment] 2024-04-03 13:54
> @4evermaat @lunarwolfspirit @beifangpoi Did you guys use any other crack to activate IDM? Did you ensure that IDM was installed using original installer and then freeze trial option was applied?

Nope.  Havent touched IDM install since running IAS some weeks ago.  Got the occasional "would you like to register" popup.  But never an end of trial/payment popup. 

Will Revo remove / reinstall / freeze / revert.

**Comment by AR-Project** [comment] 2024-04-03 14:25
At first I tought i can ignore it. But by quick observation, this pop up shows exactly every 20 minutes, blocking display and always on top of everything what I do.

**Comment by M-Hassan-Raza** [comment] 2024-04-03 15:51
I wasn't bothered by registration pop-ups when I froze the trial using IAS, as I could ignore it when it came up once in a while. However, this price pop-up is getting too obstructive to ignore. It completely blocks the view and disrupts the workflow at regular intervals. Hope some fix is in the works :)

**Comment by mememet** [comment] 2024-04-03 19:14
Same issue after update to 6.42b7.
I have 6.42b6, do overwrite it and this popup seems to disappeared.

**Comment by emikoyamasaki** [comment] 2024-04-04 00:04
Update, it's been a while and I haven't seen the pop up yet. I didn't do anything.

**Comment by ForcedToRock** [comment] 2024-04-04 00:55
I've seen the popup several times. Did a full uninstall, re-install, used the script, the popups still happened.

**Comment by MyKareee** [comment] 2024-04-04 05:36
I re-install and use the freeze trial... The popup comes back after a day... maybe it is different from everyone... will try to wait first if there is another pop up and report it here.

**Comment by megakarlach** [comment] 2024-04-04 06:05
Right now I also have the issues aswell, after updating it to Patch 7 with the original IDM (aka no other cracks), as of today I'm using lrepacks.net repacked version then patching it with IDM Freeze Trial, so far I never got this message for few days now.

**Comment by tkw829** [comment] 2024-04-04 09:29
Running into the same issue.
I am trying a clean uninstall + removing all registry entries and then a re-install.  Will update.

**Comment by AR-Project** [comment] 2024-04-04 15:13
Can confirm it also happen after I rolling back up to 6.41b22. My current solution is just close the main app, when not used.

**Comment by alirezafarvardin** [comment] 2024-04-04 16:46
Same issue after update to 6.42b7.

**Comment by tkw829** [comment] 2024-04-04 19:53
So far I have had no issue.

I believe removing the registry entries are the key.

**Comment by ForcedToRock** [comment] 2024-04-04 19:56
> So far I have had no issue.
> 
> I believe removing the registry entries are the key.

How do you do that?

**Comment by WindowsAddict** [comment] 2024-04-04 22:42
@ForcedToRock use reset option in the script

**Comment by SubmitCodes** [comment] 2024-04-05 00:05
Okay so unfortunately the same thing is happening to me and yeah I think it may have started a week ago.

So I deleted IDM, deleted any file related to it using the app [EveryThing] and manually deleted registry keys.

Then I also ran the reset trial script from the menu just to be sure, then I installed IDM normally, exited from it after launch, reset trial, freeze trial and then installed some video with it.

So far so good until... I restarted my pc to check if it will still not show a pop-up... the pop-up appeared just after I tried installing a video...at least it still works right ? Right ?

**Comment by ForcedToRock** [comment] 2024-04-05 03:28
I used the reset option and the popup still appeared.

**Comment by 4evermaat** [comment] 2024-04-05 03:54
> > @4evermaat @lunarwolfspirit @beifangpoi Did you guys use any other crack to activate IDM? Did you ensure that IDM was installed using original installer and then freeze trial option was applied?
> 
> Nope. Havent touched IDM install since running IAS some weeks ago. Got the occasional "would you like to register" popup. But never an end of trial/payment popup.
> 
> Will Revo remove / reinstall / freeze / revert.

I used Revo Uninstaller to completely clear all previous IDM registry entries.  Rebooted, then reinstalled IDM downloaded 2 days ago and ran IAS option 3 first, then rebooted, then ran option 1.  Seems to have worked.   But need to download some more files and see if it reappears.

**Comment by tkw829** [comment] 2024-04-05 14:39
Here is another way to remove IDM registry entries:

[https://gist.github.com/nameldk/a5e72c94e3246d7cbb724613219ffad5](url)

**Comment by herovaxy** [comment] 2024-04-06 03:00
I have the same issue as well.

Previously, I had the cracked version BUT I already uninstalled it and re-installed a new clean version and apply this patch.

But still showing the trial expired message.

**Comment by ltsnow** [comment] 2024-04-06 03:56
The newest Ali.Dbg Crack 19.5 patch works.  Here are the changelogs:
== Change Log v19.5 ==
  * Remove IDMGrHlp.exe fakeSN Nag
  * Optional UnSigner/Music
  * ADD Trial Reset Source
    to IDM Utility Menu 
  * Other Improvement 
  * Build #1 CRC32 > 72566dae
== Change Log v19.4 ==
  + Remove New TrialExpired Nag
  + Random Playlist Chiptune
  * Minor Improvement 
  * Build #1 CRC32 > 9ef41cdb
  * Build #2 CRC32 > a0b882ef
The first change in 19.4 is the one that fixes it.

**Comment by ltsnow** [comment] 2024-04-06 04:02
The newest Ali.Dbg Crack 19.5 patch works.
== Change Log v19.4 ==
  + Remove New TrialExpired Nag

**Comment by herovaxy** [comment] 2024-04-06 05:18
> The newest Ali.Dbg Crack 19.5 patch works. == Change Log v19.4 ==
> 
> * Remove New TrialExpired Nag

Where to find it

**Comment by ltsnow** [comment] 2024-04-06 08:06
> > The newest Ali.Dbg Crack 19.5 patch works. == Change Log v19.4 ==
> > 
> > * Remove New TrialExpired Nag
> 
> Where to find it

Here is where I got it:
https://cracksurl.com/internet-download-manager/

**Comment by HUNG-rushb** [comment] 2024-04-06 17:11
I have the same issue. I have unistalled, installed again, freezed trial using option 1, everything was fine until I downloaded 1 video , then the pop ups appeared again. I haven't found the way to work around it yet.

**Comment by HUNG-rushb** [comment] 2024-04-06 17:13
> > > The newest Ali.Dbg Crack 19.5 patch works. == Change Log v19.4 ==
> > > 
> > > * Remove New TrialExpired Nag
> > 
> > 
> > Where to find it
> 
> Here is where I got it: https://cracksurl.com/internet-download-manager/

I tried to download and it said that might be virus.

![image](https://github.com/WindowsAddict/IDM-Activation-Script/assets/57101685/0de1aab3-61f4-4591-b3c8-8ebb1fc84189)

**Comment by ltsnow** [comment] 2024-04-06 21:25
It's not a virus.  I've been using his patch for years.

**Comment by herovaxy** [comment] 2024-04-07 00:04
> > > > The newest Ali.Dbg Crack 19.5 patch works. == Change Log v19.4 ==
> > > > 
> > > > * Remove New TrialExpired Nag
> > > 
> > > 
> > > Where to find it
> > 
> > 
> > Here is where I got it: https://cracksurl.com/internet-download-manager/
> 
> I tried to download and it said that might be virus.
> 
> ![image](https://private-user-images.githubusercontent.com/57101685/320221776-0de1aab3-61f4-4591-b3c8-8ebb1fc84189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDgzODUsIm5iZiI6MTcxMjQ0ODA4NSwicGF0aCI6Ii81NzEwMTY4NS8zMjAyMjE3NzYtMGRlMWFhYjMtNjFmNC00NTkxLWIzYzgtOGViYjFmYzg0MTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAwMDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NTY2NzQyNzZhMjMxY2JhM2YyYmU2Y2Q0OGQ4MzU1MTEwNmMyMGRhZTJmNWZiOWQ3ZjhmZjA2YTkxMzczYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Re5530nlcqwksgyWVz0PVqSCWtOoECh0ejPseW9hBg)

Can confirmed that I ran Malwarebytes and found nothing after the installation. I downloaded one 18GB file and there's no message pop up anymore when using that crack by Ali.Dbg. It's false positive when downloading the file.

The crack itself has auto update as well in case Ali.Dbg updates it.

**Comment by ltsnow** [comment] 2024-04-07 00:23
> > > > > The newest Ali.Dbg Crack 19.5 patch works. == Change Log v19.4 ==
> > > > > 
> > > > > * Remove New TrialExpired Nag
> > > > 
> > > > 
> > > > Where to find it
> > > 
> > > 
> > > Here is where I got it: https://cracksurl.com/internet-download-manager/
> > 
> > 
> > I tried to download and it said that might be virus.
> > ![image](https://private-user-images.githubusercontent.com/57101685/320221776-0de1aab3-61f4-4591-b3c8-8ebb1fc84189.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDgzODUsIm5iZiI6MTcxMjQ0ODA4NSwicGF0aCI6Ii81NzEwMTY4NS8zMjAyMjE3NzYtMGRlMWFhYjMtNjFmNC00NTkxLWIzYzgtOGViYjFmYzg0MTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAwMDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NTY2NzQyNzZhMjMxY2JhM2YyYmU2Y2Q0OGQ4MzU1MTEwNmMyMGRhZTJmNWZiOWQ3ZjhmZjA2YTkxMzczYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Re5530nlcqwksgyWVz0PVqSCWtOoECh0ejPseW9hBg)
> 
> Can confirmed that I ran Malwarebytes and found nothing after the installation. I downloaded one 18GB file and there's no message pop up anymore when using that crack by Ali.Dbg. It's false positive when downloading the file.
> 
> The crack itself has auto update as well in case Ali.Dbg updates it.

I never realized that it had an auto update.  Thanks.

**Comment by lunarwolfspirit** [comment] 2024-04-07 01:04
> @lunarwolfspirit Let me know if you get the popup again.

I booted PC up today and popups have returned. Was good for the last few days.

**Comment by dfmjndm** [comment] 2024-04-07 09:43
same issue，it poped up every 10 minutes. Freezen seems not work now.

**Comment by zbabyz** [comment] 2024-04-07 10:52
Confirm that same issue from previous comment. Its make me annoying with popup. 

I did full uninstall and fresh install new IDM then run script for freeze activation. Thank you. please fix it.

I heard Ali.Dbg is good fix with crack tool without auto update. why dont you investigative for his tool?|

Note:
I haven't tired Ali.Dbg's tool now. 

![image](https://github.com/WindowsAddict/IDM-Activation-Script/assets/46247128/1a43fdc3-2769-4a99-94a9-09dd23bb9880)

**Comment by BuntyMc** [comment] 2024-04-07 14:52
I've tried the Ali.Dbg crack. It works perfectly. I prefer the IDM Activation Script because I'd rather know what was going on with a crack, but this will do until we get a fix from WindowsAddict.

**Comment by 4evermaat** [comment] 2024-04-08 10:04
> After receiving the popup today, I chose `#3` reset trial option. Then chose `#1` freeze trial.
> No uninstall/reinstall and no computer restart in between.
> Let's see what happens.

👎  A few hours later, got the popup to pay.   I've tried to reinstall IDM only (no uninstall first);  nothing else.  

Let's see what happens.

**Comment by WindowsAddict** [comment] 2024-04-09 00:56
**Notice:**
This project has been archived and is no longer being maintained.
I've switched to [HTTP Downloader](https://rentry.co/HTTP_Downloader), don't want to keep up with IDM new nags anymore.

**Closed by WindowsAddict** 2024-04-09 00:56 UTC
