### ISSUE TITLE
Fake Serial Number Appeared Again As Per 02/02/2024

### ISSUE THREAD

**Issue by cyberboh** [WindowsAddict/IDM-Activation-Script#17] opened 2024-02-03 13:32 UTC
IAS 1.0
Windows 10 x64
IDM 6.42b3 Retail

Fake serial number nag screen appear since yesterday. Applied IAS 1.0 to activate, it's gone. But then after rebooted PC , its appeared since yesterday till now.

**Comment by WindowsAddict** [comment] 2024-02-03 14:56
Hi @cyberboh 
I'm trying to find the cause, will share an update later.

**Comment by MonfGeiger** [comment] 2024-02-04 21:14
IAS 1.0
Windows 10 Pro (64-Bit)
IDM 6.42b3, same as cyberboh, freshly downloaded from the website itself
Web Browser: Firefox (64-Bit, v122)

to partially piggy back off this thread here, I've been using this since the one other tool i've been using has seemingly not been managing to stop the fake serial number notice

i've uninstalled idm with revo uninstaller pro, scanned for any loose registry entries, and cleaned any leftovers left behind, reinstalled IDM, used THIS script, and.....i can get about....two, maybe three downloads in before it flags the fake serial number notice. I don't know, but.....maybe it might have something to do with the browser extensions for this program that allow it to fetch said download links. maybe it uses that extension/addon somehow as another method to check for Serial Number Validity?

**Comment by WindowsAddict** [comment] 2024-02-04 23:36
To identify the cause, I first need to replicate it, and so far it's not appearing for me. It once did but then I applied the script and since then no popup appeared.

**Comment by MonfGeiger** [comment] 2024-02-05 02:04
that usually is enough for the nag screen to appear. back when i used the IDM Tweak tool, that screen NEVER showed, not even for an entire year, but lately it takes a few downloads then some time in-between for it to happen

**Comment by Nirzak** [comment] 2024-02-05 13:16
It's also started appearing for me. Worked well for about three months. But showing since today

**Comment by MrRubberDucky** [comment] 2024-02-06 11:24
Got jumpscared by one today, been fine for few months otherwise.

**Comment by MaxCrazy1101** [comment] 2024-02-06 17:58
It's also started appearing for me.

**Comment by Jev1337** [comment] 2024-02-06 19:51
I got this today also!

**Comment by Tboone002** [comment] 2024-02-07 01:13
Same here got my first nag screen about an hr ago, been using no problems for several months though. Just re-ran the script, didn't uninstall or anything, but haven't got another after a few downloads.

**Comment by hxuoc** [comment] 2024-02-07 12:16
Hi @WindowsAddict 
How about writing a script that automatically resets idm's 30-days trial when it is about to expire? After all, sooner or later, such serial numbers for activation will be discovered and banned by idm officials. At the moment, the scripts I found on github that claim to automatically reset the idm's trial don't seem to be able to do so, only manually.

**Comment by hani-yassine** [comment] 2024-02-07 22:16
Same for me here been using the script for 5 + months no problem (i update it when they ask for update if that helps)

**Comment by Tboone002** [comment] 2024-02-08 03:10
> Same here got my first nag screen about an hr ago, been using no problems for several months though. Just re-ran the script, didn't uninstall or anything, but haven't got another after a few downloads.

Just to update: I haven't seen the serial number nag since I re-ran script, but I am getting a new one that mentions my trial expire in X days after several downloads. I got that one ~8-10 times last night. But I did download a decent amount of files in that time, without any other problems. I'll see if clean installing does anything for tomorrow. Don't recall seeing either of these screens in around 5 months been using IDM, maybe this trial one one other time in beginning or something.

**Comment by MrRubberDucky** [comment] 2024-02-08 15:03
Something I've found last night, a workaround if you will. At least seems to work reliably for me, might also just be placebo but doesn't hurt to share.

If you get a nag screen, don't close it. 

1. Go to your browser and turn off IDM extension. 
2. Accept the nag (nothing should pop up afterwards, at least in my experience and even if it does just close out of it) 
3. Download 3 files manually
4. Enable the IDM browser extension again

Probably not permanent solution to this problem but I didn't get prompted for entire day afterwards.

**Comment by MonfGeiger** [comment] 2024-02-08 22:51
you know, i ALWAYS wondered about that nag screen saying "if you don't register it properly, downloads might be corrupted and/or fail". has that REALLY happened to anyone at all, or is all of that just nothing more but fake blustering?

also, just to sort of keep on topic, i did get the nag screen, again, after trying to space out my downloads using IDM. makes me think that beyond whatever checking/verificating setup its using, maybe its targeting other registry entries that the script isn't covering? or maybe its a hidden file/set of files on the system its using as part of the register process....or maybe the SN its using ran out? i don't know, i ain't got no proper knowledge, im just throwing ideas at the wall and seeing which plops to the ground and which one sticks

**Comment by WindowsAddict** [comment] 2024-02-09 07:32
Updated the script to v1.1
- Removed the activation option and replaced it with the Freeze trial option to lock the 30-day trial period for the lifetime.

**Comment by Dusk-Golem** [comment] 2024-02-09 15:14
> Updated the script to v1.1
> 
> * Removed the activation option and replaced it with the Freeze trial option to lock the 30-day trial period for the lifetime.

Mate, did you faced this issue yourself? I am using IDM 6.42 build 3, activated with your tool and I have still not seen the nag screen even once.

I request you to kindly restore the activation function and add the trial freeze as another option (highlight it recommended for future users or ones facing the problem). How about it?

Also, I am using windows 10 22H2 19045.3930 and browsers I use are chrome and firefox. Not once have I seen any issue with this tool. I was previously using IDM Tweak Assistant v22.6.9.0 by BamBang and even though I had no issues with it as well, I would prefer an opensource alternative anytime. Your tool has been working phenomenal for me so thanks alot.

**Comment by WindowsAddict** [comment] 2024-02-09 16:07
@Dusk-Golem The popup is reproducible, to do that, you just need to download lots of files. I'll enable this option back when I'll figure out the workaround.

**Comment by Flwk** [comment] 2024-02-09 16:29
Well, the pop-up for fake also showed up for me. I hope a solution will be found :)

**Comment by WindowsAddict** [comment] 2024-02-09 16:39
@Dusk-Golem Go to any Reddit page, do Ctrl + A, and right click an download the selected links, do this 2-3 times in different pages so that the download links numbers are at least 70-80, and then wait some time, popup should appear.

**Comment by Dusk-Golem** [comment] 2024-02-09 17:45
> @Dusk-Golem Go to any Reddit page, do Ctrl + A, and right click and select download the selected links, do this 2-3 times in different pages so that the download links numbers are at least 70-80, and then wait some time, popup should appear.

Tried it and yes, I did get the nag screen.

**Comment by MrRubberDucky** [comment] 2024-02-09 18:28
> > @Dusk-Golem Go to any Reddit page, do Ctrl + A, and right click and select download the selected links, do this 2-3 times in different pages so that the download links numbers are at least 70-80, and then wait some time, popup should appear.
> 
> Tried it and yes, I did get the nag screen.
> 
> EDIT: IDM is still working normally even after getting the nag screen, lol. I downloaded 3 youtube videos after getting the nag screen and it works as usual. WTF 🤣 .

It still works if you don't mind closing nag screens that start appearing more often, they can be pretty disruptive and quite annoying while working on something or even playing games.

**Comment by Dusk-Golem** [comment] 2024-02-09 18:33
> > > @Dusk-Golem Go to any Reddit page, do Ctrl + A, and right click and select download the selected links, do this 2-3 times in different pages so that the download links numbers are at least 70-80, and then wait some time, popup should appear.
> > 
> > 
> > Tried it and yes, I did get the nag screen.
> > EDIT: IDM is still working normally even after getting the nag screen, lol. I downloaded 3 youtube videos after getting the nag screen and it works as usual. WTF 🤣 .
> 
> It still works if you don't mind closing nag screens that start appearing more often, they can be pretty disruptive and quite annoying while working on something or even playing games.

I clean installed IDM so I am ok for now and I don't usually download 80+ files at once so I am not worried. Also, there is already a fix so...

**Comment by Flwk** [comment] 2024-02-09 18:35
> > > > @Dusk-Golem Go to any Reddit page, do Ctrl + A, and right click and select download the selected links, do this 2-3 times in different pages so that the download links numbers are at least 70-80, and then wait some time, popup should appear.
> > > 
> > > 
> > > Tried it and yes, I did get the nag screen.
> > > EDIT: IDM is still working normally even after getting the nag screen, lol. I downloaded 3 youtube videos after getting the nag screen and it works as usual. WTF 🤣 .
> > 
> > 
> > It still works if you don't mind closing nag screens that start appearing more often, they can be pretty disruptive and quite annoying while working on something or even playing games.
> 
> I clean installed IDM so I am ok for now and I don't usually download 80+ files at once so I am not worried. Also, there is already a fix so...

where is a fix ? The freeze thing is only temporary no ?

**Comment by WindowsAddict** [comment] 2024-02-09 18:37
@Flwk Freeze trial thing is good enough, at least for me. You won't have to run the script again to reset the trial as it will always remain at 30 30-day period.

**Comment by leorcdias** [comment] 2024-02-10 01:01
@WindowsAddict it's normal for the registration screen to appear every time when opening the idm after v1.1 freeze?

**Comment by WindowsAddict** [comment] 2024-02-10 01:28
@leorcdias No.

**Comment by vhick** [comment] 2024-02-10 02:02
Same here, two nag screen appeared on the first launch of idm. One is the registration popup, second is notification that you are in trail versioin.

**Comment by MrRubberDucky** [comment] 2024-02-10 02:37
> Same here, two nag screen appeared on the first launch of idm. One is the registration popup, second is notification that you are in trail versioin.

Same behaviour for me. After each reboot it likes to nag with that again. Saw it earlier after applying the freeze patch but thought it was intentional so I just clicked through it 😅 

That said, would a clean install of IDM with the freeze patch applied fix this? Since all I did was reset activation / trial from the script and then froze the trial so maybe it just didn't do something extra, tad clueless on this one.

**Comment by WindowsAddict** [comment] 2024-02-10 03:35
Occasional notification that you are in trial mode is expected, but it doesn't appear after every reboot or IDM restart, It hasn't appeared for me at least in the last 2 days. 

Anyway, closing this thread here.

**Comment by WindowsAddict** [comment] 2024-02-10 12:14
https://github.com/WindowsAddict/IDM-Activation-Script/issues/19#issuecomment-1936992176

Please test and share results.

**Comment by Dusk-Golem** [comment] 2024-02-10 13:42
> [#19 (comment)](https://github.com/WindowsAddict/IDM-Activation-Script/issues/19#issuecomment-1936992176)
> 
> Please test and share results.

I just tried this. Clean installed IDM for this test by resetting IDM first and then uninstalling with Revo Uninstaller, followed by a reboot. Still getting the nag screen after multiple downloads from a reddit page. Guess, this is a tricky one to bypass.

**Comment by WindowsAddict** [comment] 2024-02-10 14:19
@Dusk-Golem I added v2 there, please try that.

**Comment by vhick** [comment] 2024-02-10 16:35
Just to report, I clean uninstall idm with hibit uninstaller and regsitry trash key finder. Use the trial installer from the website (don't use retail installer, freeze with v1.1 and the two nag screen that I experience disappeared. I download some iso to test and I still not experience any nag screen. I will monitor if the nag screen will show. Thank you @WindowsAddict !

**Closed** 2024-02-11 19:06 UTC
